"use client";

import { useEffect, useMemo, useState } from 'react';

type Lead={id:string;first:string;last:string;phone:string;city:string;profile:string;animals:string[];identification:string;onsite:boolean;score:number;gift:string;createdAt:string;sync:'Synchronise'|'En attente'};
const profiles=['Eleveur','Veterinaire','Proprietaire animaux','Professionnel animal','Institution','Etudiant','Visiteur'];
const animals=['Bovins','Ovins','Caprins','Porcins','Volailles','Chiens','Chats','Chevaux'];
const games=['Scanner VetTronic','Retrouve mon proprietaire','A qui appartient ce troupeau','Stop epidemie','Marche aux animaux','Sauve ton elevage','Mission veterinaire','Qui suis-je','Defi identification','Alerte betail','Patient zero'];
function gift(score:number){if(score>=100)return'Lot premium';if(score>=80)return'T-shirt';if(score>=70)return'Casquette';if(score>=50)return'Stylo';return'Participation';}
export default function App(){const[screen,setScreen]=useState<'home'|'form'|'game'|'result'|'admin'>('home');const[step,setStep]=useState(0);const[leads,setLeads]=useState<Lead[]>([]);const[start]=useState(Date.now());const[actions,setActions]=useState<string[]>([]);const[form,setForm]=useState({first:'',last:'',phone:'',city:'',profile:'Eleveur',animals:[] as string[],identification:'Je ne sais pas',onsite:false});
useEffect(()=>{setLeads(JSON.parse(localStorage.getItem('vettronic-leads')||'[]'));if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
function saveLead(){const pct=Math.min(100,Math.round(actions.length/5*100));const lead:Lead={id:crypto.randomUUID(),...form,score:pct,gift:gift(pct),createdAt:new Date().toISOString(),sync:navigator.onLine?'Synchronise':'En attente'};const next=[lead,...leads];localStorage.setItem('vettronic-leads',JSON.stringify(next));setLeads(next);setScreen('result');}
const game=useMemo(()=>games[(form.profile.length+form.first.length)%games.length],[form.profile,form.first]);
if(screen==='admin')return <main className="min-h-screen p-5"><Top go={()=>setScreen('home')}/><h1 className="text-3xl font-black mb-4">Admin SELAB</h1><div className="grid grid-cols-4 gap-3 mb-5 grid2"><Stat k="Participants" v={leads.length}/><Stat k="En attente" v={leads.filter(l=>l.sync==='En attente').length}/><Stat k="Cadeaux" v={leads.filter(l=>l.gift!=='Participation').length}/><Stat k="Priorites" v={leads.filter(l=>l.profile==='Eleveur'||l.onsite).length}/></div><button onClick={()=>{const csv='Nom,Telephone,Ville,Profil,Score,Cadeau\n'+leads.map(l=>`${l.first} ${l.last},${l.phone},${l.city},${l.profile},${l.score},${l.gift}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='vettronic-leads.csv';a.click();}} className="tap rounded bg-tech px-5 py-3 font-black text-white mb-4">EXPORTER CSV</button><div className="overflow-auto rounded border bg-white"><table className="w-full min-w-[760px] text-left"><thead className="bg-field"><tr>{['Nom','Telephone','Ville','Profil','Identification','Sur site','Score','Cadeau'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{leads.map(l=><tr className="border-t" key={l.id}><td className="p-3 font-bold">{l.first} {l.last}</td><td className="p-3">{l.phone}</td><td className="p-3">{l.city}</td><td className="p-3">{l.profile}</td><td className="p-3">{l.identification}</td><td className="p-3">{l.onsite?'Oui':'Non'}</td><td className="p-3">{l.score}%</td><td className="p-3">{l.gift}</td></tr>)}</tbody></table></div></main>;
if(screen==='game')return <main className="min-h-screen bg-field p-5"><Top go={()=>setScreen('home')}/><section className="mx-auto max-w-4xl"><p className="font-bold text-tech">Jeu selectionne</p><h1 className="text-4xl font-black mb-5">{game}</h1><div className="grid grid-cols-2 gap-5 grid2"><div className="rounded bg-white p-5 shadow"><div className="text-8xl text-center py-8">🐄</div><p className="rounded bg-ink p-4 text-white font-black">BIP - IDENTIFICATION TROUVEE</p></div><div className="grid gap-3">{['Scanner animal','Verifier boucle','Consulter dossier','Confirmer proprietaire','Tracer historique'].map(a=><button key={a} onClick={()=>setActions(x=>x.includes(a)?x:[...x,a])} className={'tap rounded border px-4 py-3 text-left font-black '+(actions.includes(a)?'bg-leaf text-white':'bg-white')}>{a}</button>)}<button onClick={saveLead} className="tap rounded bg-tech py-4 text-xl font-black text-white">TERMINER</button></div></div></section></main>;
if(screen==='result')return <main className="min-h-screen grid place-items-center bg-field p-5"><section className="max-w-xl rounded bg-white p-8 text-center shadow"><img src="/branding/logo.png" className="mx-auto h-24 object-contain" alt="VetTronic"/><h1 className="text-4xl font-black mt-4">Bravo {form.first}</h1><p className="text-2xl font-black text-tech mt-3">Score {leads[0]?.score}%</p><p className="text-xl mt-2">Cadeau : {leads[0]?.gift}</p>{form.onsite&&<p className="mt-3 rounded bg-field p-3 font-bold text-leaf">Eligible identification gratuite sur le SELAB</p>}<button onClick={()=>{setForm({first:'',last:'',phone:'',city:'',profile:'Eleveur',animals:[],identification:'Je ne sais pas',onsite:false});setActions([]);setStep(0);setScreen('home')}} className="tap mt-6 rounded bg-tech px-6 py-4 font-black text-white">NOUVEAU PARTICIPANT</button></section></main>;
if(screen==='form')return <main className="min-h-screen bg-field p-5"><Top go={()=>setScreen('home')}/><section className="mx-auto max-w-2xl rounded bg-white p-5 shadow"><h1 className="text-3xl font-black mb-4">Participation</h1>{step===0&&<div className="grid gap-3"><Input p="Prenom" v={form.first} f={v=>setForm({...form,first:v})}/><Input p="Nom" v={form.last} f={v=>setForm({...form,last:v})}/><Input p="Telephone" v={form.phone} f={v=>setForm({...form,phone:v})}/><Input p="Ville" v={form.city} f={v=>setForm({...form,city:v})}/><button disabled={!form.first||!form.last||!form.phone||!form.city} onClick={()=>setStep(1)} className="tap rounded bg-tech py-4 font-black text-white disabled:opacity-40">VALIDER</button></div>}{step===1&&<div><p className="font-black mb-3">Vous etes principalement :</p><div className="grid gap-2">{profiles.map(p=><button onClick={()=>setForm({...form,profile:p})} className={'tap rounded border px-4 py-3 text-left font-black '+(form.profile===p?'bg-tech text-white':'bg-white')} key={p}>{p}</button>)}</div><button onClick={()=>setStep(2)} className="tap mt-4 rounded bg-tech py-4 w-full font-black text-white">CONTINUER</button></div>}{step===2&&<div><p className="font-black mb-3">Animaux possedes ou geres :</p><div className="grid grid-cols-2 gap-2">{animals.map(a=><button onClick={()=>setForm({...form,animals:form.animals.includes(a)?form.animals.filter(x=>x!==a):[...form.animals,a]})} className={'tap rounded border px-3 py-3 font-bold '+(form.animals.includes(a)?'bg-tech text-white':'bg-white')} key={a}>{a}</button>)}</div><select value={form.identification} onChange={e=>setForm({...form,identification:e.target.value})} className="tap mt-4 w-full rounded border px-3"><option>Oui, tous</option><option>Oui, en partie</option><option>Non</option><option>Je ne sais pas</option></select><label className="mt-4 flex items-center gap-3 font-bold"><input type="checkbox" checked={form.onsite} onChange={e=>setForm({...form,onsite:e.target.checked})}/> Animal present au SELAB</label><button onClick={()=>setScreen('game')} className="tap mt-4 rounded bg-tech py-4 w-full font-black text-white">LANCER LE JEU</button></div>}</section></main>;
return <main className="min-h-screen bg-[linear-gradient(135deg,#f7fbf8,#dff5e7)] p-5"><header className="mx-auto flex max-w-5xl items-center justify-between"><img src="/branding/logo.png" className="h-24 object-contain" alt="VetTronic"/><button onClick={()=>setScreen('admin')} className="text-sm text-ink/50 underline">Admin</button></header><section className="mx-auto max-w-5xl py-12"><p className="mb-5 inline-block rounded-full bg-white px-4 py-2 font-bold text-tech">2 minutes - Gratuit - Cadeaux a gagner</p><h1 className="hero max-w-3xl text-7xl font-black leading-tight">RELEVEZ LE DEFI VET'TRONIC</h1><p className="mt-5 max-w-2xl text-xl text-ink/70">Testez vos connaissances, protegez vos animaux et tentez de gagner des cadeaux.</p><button onClick={()=>setScreen('form')} className="tap mt-8 rounded bg-tech px-12 py-5 text-2xl font-black text-white">JOUER</button></section></main>}
function Top({go}:{go:()=>void}){return <button onClick={go} className="mb-5 text-sm font-bold text-tech">← Accueil</button>}
function Input({p,v,f}:{p:string;v:string;f:(v:string)=>void}){return <label className="grid gap-1 font-bold">{p}<input value={v} onChange={e=>f(e.target.value)} className="tap rounded border px-3"/></label>}
function Stat({k,v}:{k:string;v:number}){return <div className="rounded bg-white p-4 shadow"><p className="font-bold text-ink/60">{k}</p><p className="text-3xl font-black text-tech">{v}</p></div>}
